#
# Steps for building and testing Jest. See jobs defined in .azure-pipelines.yml
#

steps:
  - checkout: self
    path: jest

  # Ensure Node.js 12 is active
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Use Node.js 12'

  # Ensure Python 2.7 is active
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
    displayName: 'Use Python 2.7'

  - bash: echo "##vso[task.setvariable variable=folder;isOutput=true]$(yarn config get cacheFolder)"
    name: yarnCache

  - task: Cache@2
    inputs:
      key: yarn | $(Agent.OS) | yarn.lock
      path: $(yarnCache.folder)
    displayName: Cache Yarn packages

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn build:js
    displayName: 'Transpile TypeScript'

  # Run test-ci-partial
  - script: yarn run test-ci-partial
    displayName: 'Run tests'

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/reports/junit/*.xml'
      testRunTitle: 'CI Tests $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()
