enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@docusaurus/plugin-pwa@*":
    peerDependencies:
      "@babel/core": "^7.0.0"
  "docusaurus-plugin-sass@*":
    peerDependencies:
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
