enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
